name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [20.x]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - name: install modules
              run: npm install
            - name: Check if the file exists
              run: |
                  ls src/pages/CounterPage
            - name: List project files
              run: |
                  echo "Listing all project files:"
                  ls -R
            - name: Check node version
              run: node -v
            - name: Check npm version
              run: npm -v
            - name: List installed packages
              run: npm ls

            - name: build production project
              run: npm run build:prod
            - name: linting typescript
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:scss
            - name: unit testing
              run: npm run test:unit
